# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9b339d7e14227f88c91a343e975bb607f6c5cf8b3b817bae3956578eae00e6eb6a9509a09f499581832d671280cfe78c4827f9a2987549b0dcbcdd31c79f827

test:
  secret_key_base: 5141dfb4e99cb8b79d9ef482c21cf70db86edeafdfc20d3ea068620b9eb03e8976294342a4688df17ba0592f6636e472e80c25bec98f268452d2a7f9c7c0c5e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
